### ISSUE TITLE
Latest rates stuck on 2018-09-06

### ISSUE THREAD

**Issue by LorrieMonaghan** [exchangeratesapi/exchangeratesapi#22] opened 2018-09-10 16:27 UTC
If I request the latest rates using https://api.exchangeratesapi.io/latest the API is only returning rates from the 2018-09-06 onward.

The same thing happens if I request historical data, I can get all the rates up until 2018-09-06 only. Any historical date requests post this date incorrectly return the rates for 2018-09-06.

**Comment by acs-ferreira** [comment] 2018-09-10 16:29
Maybe cache. Here on my own deployed instance (same code), i get rates from 2018-09-10.

![image](https://user-images.githubusercontent.com/12234510/45310772-81277980-b527-11e8-9cd2-4e00cab20de4.png)

**Comment by kekridk** [comment] 2018-09-11 10:51
I have the same issue. @madisvain - is this something you can look into, please? Are your servers running as expected?

**Comment by tainmar** [comment] 2018-09-11 10:52
I also have the same issue. I ended up deploying on Heroku (via the button on Readme). It works smoothly.

**Comment by deefrawley** [comment] 2018-09-12 03:46
I'm using Python requests (no caching module) and am also only getting results from Sep 6th. @tainmar are you saying since deploying on Heroku you are getting the latest data?

**Comment by tainmar** [comment] 2018-09-12 07:45
@deefrawley that is indeed what I am saying. **I am getting the latest price from my Heroku instance**.

Honestly, I am pretty sure that [https://exchangeratesapi.io](https://exchangeratesapi.io) has not the _exact_ same codebase as the repo here. That would explain the different API endpoint (subdomain vs subfolder). 

Anyway, you should give a try to Heroku deployment : super easy (that was my first time) and no more non-documented changes (see #20)

**Comment by johamm** [comment] 2018-09-12 09:56
I can confirm I'm getting the same issue.  Is there a chance that this will get fixed without deploying to Heroku?

**Comment by MajorDisarray** [comment] 2018-09-13 15:35
Checking in to say that I get the same issue, latest update 09-06

**Comment by deefrawley** [comment] 2018-09-15 04:06
Thanks @tainmar but a Heroku deployment is not what I'm after. I've given up on this API and am now grabbing the XML directly from the Euro bank and doing the currency conversions myself.

**Comment by ravtakhar** [comment] 2018-09-16 19:45
Same issue here everything was going great However, stuck at September 6th

**Comment by madisvain** [comment] 2018-09-17 07:36
As the issue has not been fixed I suggest also to use the https://frankfurter.app/. I handed over the exchangeratesapi.io project and it seems that it's not even running on the same codebase any more.

I feel deeply saddened by this and feel helpless to resolve the issue as I no longer have control over this project.

**Comment by madisvain** [comment] 2018-09-17 19:52
The issue will be resolved shortly and the service will continue to operate as intended.

It's possible now for me to monitor the service and provide fixes, updates to keep everything operational so we should have no more problems. I will update the state of this issue as soon as the updates have been deployed.

**Comment by madisvain** [comment] 2018-09-18 08:30
The updates have been deployed. I will continue monitoring the situation and take care of the service being available as intended.

**Closed by madisvain** 2018-09-18 08:30 UTC
